### ISSUE TITLE
v1.13.5.327-alpha essentials is clearing all settings on load in 01.127, not saving any new settings

### ISSUE THREAD

**Issue by afinegan** [SEServerExtender/EssentialsPlugin#82] opened 2016-03-24 19:05 UTC
v1.13.5.327-alpha essentials is clearing all settings on load in 01.127, not saving any new settings

error message thrown,
[essentialError.txt](https://github.com/SEServerExtender/EssentialsPlugin/files/188489/essentialError.txt)

**Comment by SilentSymphony** [comment] 2016-03-24 19:08
same here

**Comment by rexxar-tc** [comment] 2016-03-24 19:50
I know what the problem is, I should have a hotfix up this evening.

**Comment by rexxar-tc** [comment] 2016-03-25 03:45
Sorry, forgot to close this when I published the update.

There was a bug in the XML serializer that caused Essentials to erase the settings XML instead of throwing an error. If you're still getting errors after this update, you need to delete Essential-Settings.xml and start over.

I'm really sorry that bug got through, but I just never even thought to test for something like that.

**Closed by rexxar-tc** 2016-03-25 03:45 UTC
