### ISSUE TITLE
Docking Zone undock not work

### ISSUE THREAD

**Issue by eXactMatX** [SEServerExtender/EssentialsPlugin#10] opened 2015-03-30 15:41 UTC
The command /dock undock does not work, no error will be displayed.

**Comment by dodexahedron** [comment] 2015-03-31 05:00
I have not yet had a look at the docking code.  There's a reasonably high chance that recent changes to SE may have broken several chat commands.
I'll add this to my list of things to look into.
Can you try again and give me logs?

**Comment by eXactMatX** [comment] 2015-03-31 11:09
Sorry, no error messages occur during  /dock undock

2015-03-31 12:59:06.5546|Info|SEServerExtender.Program.Start|Starting SEServerExtender with 0 arguments ...
2015-03-31 12:59:06.7835|Info|SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper..ctor|Finished loading SandboxGameAssemblyWrapper
2015-03-31 12:59:07.3775|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunBaseReflectionUnitTests|All main types passed reflection unit tests!
2015-03-31 12:59:07.4657|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunEntityReflectionUnitTests|All entity types passed reflection unit tests!
2015-03-31 12:59:07.5397|Info|SEModAPIExtensions.API.BasicUnitTestManager.RunCubeBlockReflectionTests|All block types passed reflection unit tests!
2015-03-31 12:59:07.5397|Info|SEModAPIExtensions.API.Server..ctor|Finished creating server!
2015-03-31 12:59:07.5397|Info|SEModAPIInternal.API.Server.ServerAssemblyWrapper.get_Instance|Finished loading ServerAssemblyWrapper
2015-03-31 12:59:07.5608|Info|SEModAPIExtensions.API.PluginManager..ctor|Finished loading PluginManager
2015-03-31 12:59:07.5608|Info|SEModAPIInternal.API.Common.FactionsManager.get_Instance|Finished loading FactionsManager
2015-03-31 12:59:07.5608|Info|SEModAPIInternal.API.Common.EntityEventManager.get_Instance|Finished loading EntityEventManager
2015-03-31 12:59:07.5818|Info|SEModAPIExtensions.API.ChatManager..ctor|Finished loading ChatManager
2015-03-31 12:59:07.5848|Info|SEServerExtender.Program.Start|Opening up WCF service listener
2015-03-31 12:59:25.1636|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Loading Session Settings
2015-03-31 12:59:27.7700|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|
Max Players: 50
2015-03-31 12:59:27.7720|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|OnlineMode: OFFLINE
2015-03-31 12:59:27.7720|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|GameMode: Creative
2015-03-31 12:59:27.7720|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|Scenario: Asteroids
2015-03-31 12:59:27.7720|Info|SEModAPIExtensions.API.SessionManager.UpdateSessionSettings|World Size: 0

2015-03-31 12:59:27.8892|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading PlayerManager
2015-03-31 12:59:27.8892|Info|SEServerExtender.SEServerExtender.ChatViewRefresh|Finished loading NetworkManager
2015-03-31 12:59:30.1108|Info|SEModAPIInternal.API.Common.PlayerMap.get_Instance|Finished loading PlayerMap
2015-03-31 13:00:05.7683|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Loading plugins ...
2015-03-31 13:00:05.7733|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Scanning: C:\ProgramData\SpaceEngineersDedicated\SpaceEngineers\Mods
2015-03-31 13:00:05.7733|Info|SEModAPIExtensions.API.PluginManager.LoadPlugins|Finished loading plugins
2015-03-31 13:00:05.7733|Info|SEModAPIExtensions.API.PluginManager.Init|Initializing plugins ...
2015-03-31 13:00:05.7894|Info|SEModAPIExtensions.API.PluginManager.InitPlugin|Initializing plugin at C:\ProgramData\SpaceEngineersDedicated\SpaceEngineers\Mods\Essentials\Essentials.dll - f767bda5-0a8c-4813-85fd-a5a2341778e8'
2015-03-31 13:00:06.4069|Info|SEModAPIExtensions.API.PluginManager.Init|Finished initializing plugins
2015-03-31 13:00:10.1059|Info|SEModAPIInternal.API.Common.FactionsManager.GetSubTypeEntity|Finished loading WorldManager
2015-03-31 13:00:31.8151|Error|SEModAPIExtensions.API.PluginManager.DoUpdate|System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.TypeLoadException: Der Typ "NLog.Fluent.Log" in der Assembly "NLog, Version=3.2.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c" konnte nicht geladen werden.
   bei EssentialsPlugin.Utility.Players.Load()
   bei EssentialsPlugin.ProcessHandlers.ProcessLoginTracking.OnPlayerJoined(UInt64 remoteUserId)
   bei EssentialsPlugin.Essentials.OnPlayerJoined(UInt64 remoteUserId)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei SEModAPIExtensions.API.PluginManager.DoUpdate(Object args)
2015-03-31 13:04:28.2357|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__2|Asynchronous Save Setup Started: 460.4377ms
2015-03-31 13:04:29.6530|Info|SEModAPIInternal.API.Common.WorldManager+<>c__DisplayClass3.<AsynchronousSaveWorld>b__0|Asynchronous Save Completed: 1877,7846ms

**Comment by dodexahedron** [comment] 2015-03-31 19:06
You need to update essentials to the latest version, which fixes that issue.
Also, if you are not seeing these log messages at the console, your SEServerExtender.config file is out of date, and you need to update it from the SEServerExtender zip file.
Closing this as a duplicate of #6

**Closed by dodexahedron** 2015-03-31 19:06 UTC
Labels: duplicate
