### ISSUE TITLE
/admin scan grids ownedby:user

### ISSUE THREAD

**Issue by yaccoin** [SEServerExtender/EssentialsPlugin#6] opened 2015-03-28 22:32 UTC
Just for tracking purposes, this command is broke.

http://puu.sh/gTBTq/b1d8572045.png

**Comment by jcsims** [comment] 2015-03-28 23:37
I can confirm that the first four example commands work as expected - "scan grids",  "scan grids noterminal", "scan grids noownership", and "scan grids nopower". The other five commands all give the same error - "Possible problem with your parameters (options provided is larger than options found). Not returning results in case of error".

**Comment by dodexahedron** [comment] 2015-03-29 00:09
Thanks for the report.
Obviously I need to fix all of them, but is there an order you'd like to see them fixed?

-----Original Message-----

**Comment by yaccoin** [comment] 2015-03-29 00:18
Personally:

1)  Ability to find ships (scan grids ownedby) and move to them (move 
player)
2)  Ability to change the ownership of a ship
3)  Ability to locate idle users
4)  Everything else

**Comment by jcsims** [comment] 2015-03-29 00:43
For me, it's mostly removing the NPC ships as they tend to build up for some reason, and slow things down. So, ownedby (or if there's an easier way to get rid of the NPC ships).

**Comment by yaccoin** [comment] 2015-03-29 00:45
I use "noownership" to remove the ships, but that catches a Control Grid 
that Extender uses. Therefore I do the cleanup right before I do the 
daily restart, since the Control Grid is recreated at start time - or so 
I'm told <smile>.

**Comment by Lordicon** [comment] 2015-03-29 02:01
Not sure if I am doing this correctly but I have been creating a cleanup timer set to scan two times a day looking for this.

"hascustomname:Private Sail"
"hascustomname:Mining Carriage"
"hascustomname:Military Minelayer"
"hascustomname:Military Escort"
"hascustomname:Commercial Freighter"
"hascustomname:Business Shipment"
"hascustomname:Mining Transport"

**Comment by dodexahedron** [comment] 2015-03-30 07:15
Can you try again with the latest release and let me know how it goes?

**Comment by Odys-SE** [comment] 2015-03-31 00:58
Dodex,

I have been using the older version since I saw this post over on the KEEN forums: 
http://forums.keenswh.com/post/show_single_post?pid=1286710228&postcount=81

But I just tried your 1.7.1.2311 along with the new SESE 1.75.6.336 and I was able to load my server still and play in it, but there was an error right at the beginning of initializing plugins:
![image](https://cloud.githubusercontent.com/assets/11729023/6910329/a6598072-d70e-11e4-86ea-ad9102817d1f.png)

(Sorry for the screengrab only, fastest way to get the error message over to you right now.)

In the server I tried to run one of the admin commands with no success:

/admin scan grids excludesblocksubtype:Beacon:1

**Comment by dodexahedron** [comment] 2015-03-31 05:12
The fix I put in for #9 may have resolved this.
Once I release that in around half an hour, try version 1.7.2.2215 and let me know how it works for you.

**Comment by Odys-SE** [comment] 2015-03-31 06:35
Thank you, Dodex, I will test it right now!

--Aaron King 
(Sorry for the brevity, this was sent from my iPad)

**Comment by Odys-SE** [comment] 2015-03-31 07:00
Awesome, great news! The server initiated without any error messages AND the essentials plugin commands are working for me! 

The command I messaged about above as well as:
/admin scan grids excludesblocksubtype:EncasedGyroscope:1 

Worked out perfectly. Thank you for fixing these!! I can now do auto cleanups. 

P.S. The /admin move player position odys command is working great as well! Again, thank you so much!

**Comment by dodexahedron** [comment] 2015-03-31 19:04
Excellent.
Closing this one.

**Closed by dodexahedron** 2015-03-31 19:04 UTC
Labels: bug
