### ISSUE TITLE
Entity Management - Conceal/Reveal Loop for grids with production

### ISSUE THREAD

**Issue by TheEngineer50** [SEServerExtender/EssentialsPlugin#98] opened 2016-06-05 13:32 UTC
Grids that are revealed due to "Reason: Grid has production facility that has a queue" are in a loop of revealing and concealing. Brand new essential config with no options set other than Entity Management for grids.  

log: http://pastebin.com/raw/wtb0V4Bq

see "dwickers station" as an example

**Comment by foogs** [comment] 2016-06-05 15:23
Same problem

**Comment by Tostito** [comment] 2016-06-05 22:03
mayhaps give us an option to force production off regardless of queue status.  players will just log in to keep these rolling which is just another thing to keep grids from concealing and staying active.

**Comment by TheEngineer50** [comment] 2016-06-08 02:47
Why are we using IMyProductionBlockIsProducing in CheckConcealBlockRule but MyProductionBlock.Queue.Any in CheckRevealBlockRules? Is there a reason I don't follow? Doesn't matter really but it looks like IMyProductionBlock.IsProducing is not returning true on some of those blocks for some reason but MyProductionBlock.Queue.Any does. Seems to be working on my build anyway.  Not seeing that reveal/conceal loop anymore. Hope this helps figure it out.

An unrelated issue, and curse me for putting it here, is I am seeing some grids that are always concealing but never revealing. It's like they are not being concealed for some reason when it attempts to conceal them. It's the exact same 10 or so grids.

**Comment by rexxar-tc** [comment] 2016-06-08 04:41
Because I changed the first one and forgot to change the second ¯\_(ツ)_/¯ I'm rewriting some really old code, so these things slip through the cracks from time to time.

I noticed that as soon as I started investigating this and changed it to just check the queue. IsProducing checks if the queue is empty, so in theory it shouldn't have caused a problem. But theory and practice are very, very different in this game...

I'll check the reveal logic to see why those grids wouldn't be revealing.

**Comment by TheEngineer50** [comment] 2016-06-08 12:40
That's cool.

To clarifiy about the other issue. The grids are concealing every cycle. There is no reveal attempt on them. So it's like they are never actually concealing. I was a little vague there I guess.

**Comment by rexxar-tc** [comment] 2016-06-08 19:44
That shouldn't be possible. It tracks which grids have been concealed precisely so it won't try to conceal the same grid multiple times.

**Comment by TheEngineer50** [comment] 2016-06-08 23:42
I see that but check this out. 

https://pastee.org/rhhqx

Search for "dwicker multi ship" for example or "Static Grid 3962". It's a pretty short log. I'll poke around too.

**Comment by rexxar-tc** [comment] 2016-06-09 03:34
That's interesting. I think I know what the problem is, then.

**Comment by TheEngineer50** [comment] 2016-06-10 01:17
It appears all the grids are doing it now after the essentials update today.

**Comment by rexxar-tc** [comment] 2016-06-11 01:32
Would you mind sending me your world so I can check it out?

**Comment by TheEngineer50** [comment] 2016-06-11 14:09
The "all grids concealing over and over" issue is due to the change you made here:

"foreach (GridGroup group in GridGroup.GetAllGroups(GridLinkTypeEnum.Logical))"

At first I thought it was the change from physical to logical but that was not it. I have no freaking clue why refactoring to one line would not work. Looks like it should to me but if you separate them back out the way you had it you can still change to logical and it functions. As in not all grids are forever concealing. Now even with the change to logical there is still a group of 10 grids or so (less then what it was when physical) that are always concealing.

works ok:          
"var groups = GridGroup.GetGroups( entitiesFiltered, GridLinkTypeEnum.Logical );
foreach ( GridGroup group in groups )"

I'd love to know why your refactor to one line didn't work though, I don't understand that.

**Comment by foogs** [comment] 2016-06-11 20:19
My server big world
[GNR_StarSystem_world.zip](https://github.com/SEServerExtender/EssentialsPlugin/files/310452/GNR_StarSystem_world.zip)

**Comment by rexxar-tc** [comment] 2016-06-13 02:57
This should be fixed in the latest update. Please let me know if you still have trouble.

**Comment by TheEngineer50** [comment] 2016-06-14 00:30
I think you got both issues sorted.

**Comment by rexxar-tc** [comment] 2016-06-14 02:11
Awesome. I'm gonna close this then, feel free to reopen it if you have trouble again.

**Closed by rexxar-tc** 2016-06-14 02:11 UTC
